version: '2'
services:
  zookeeper:
    #build: .
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    #build: .
    #0.11.0.1
    #0.10.2.1
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    #networks:
    #  default:
    #    aliases:
    #      - kafka.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
